# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'cell_with_export_directive', 'cell_with_exports_directive']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 4
def cell_with_export_directive():
    print("hi")
    print("ok")
    a = 1+2
    print(a)

# %% ../nbs/00_core.ipynb 5
def cell_with_exports_directive():
    print("hi")
    print("ok")
    a = 1+2
    print(a)
